config/routes.rb
NullsixTagger::Application.routes.draw do
  resources :admins
  resources :links
  root :to => 'links#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true,
                   length: { maximum: 75 }
  validates :email, presence: true,
                    format: { with: email_regex },
                    uniqueness: { case_sensitive: false }

  validates :password, presence: true,
                       confirmation: true,
                       length: { within: 8..40 }

  before_save :encrypt_password

  # Return true if the admin's password matches the submitted password
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    admin = find_by_email(email)
    return nil if admin.nil?
    return admin if admin.has_password?(submitted_password)
  end

  private
  
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
     secure_hash("#{salt}--#{string}") 
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :url

  scope :latest, lambda { |count| order("id DESC").limit(count) }

  validates :url, :presence => true
  before_save :tag_url

  def tag_url
    self.url = tagged_url
  end
  
  private
    def tagged_url
      http_prefix

      # Don't tag a tagged link again
      return self.url if url_is_already_tagged
      
      tag_starter = url_contains_a_param_string? ? "&" : "?"
      self.url + tag_starter + "tag=nu07-20"
    end

    # Lets us use link_to and get to an extenal site
    def http_prefix
      self.url = "http://" + self.url unless self.url =~ /^http:\/\//
    end


    def url_is_already_tagged
      self.url =~ /tag=nu07-20/
    end

    def url_contains_a_param_string?
      self.url =~ /\?/ ? true : false
    end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @admins = Admin.all
  end

  def show
    @admin = Admin.find(params[:id])
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params[:admin])
    if @admin.save
      redirect_to @admin
    else
      render 'new'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  # GET /links
  # GET /links.json
  def index
    @tagged_link = Link.last
    
    @link = Link.new
    @links = Link.latest(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

#  # GET /links/1
#  # GET /links/1.json
#  def show
#    @link = Link.find(params[:id])
#
#    respond_to do |format|
#      format.html # show.html.erb
#      format.json { render json: @link }
#    end
#  end

#  # GET /links/new
#  # GET /links/new.json
#  def new
#    @link = Link.new
#
#    respond_to do |format|
#      format.html # new.html.erb
#      format.json { render json: @link }
#    end
#  end

#  # GET /links/1/edit
#  def edit
#    @link = Link.find(params[:id])
#  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { flash[:created] = "Created"; redirect_to '/' }
        #format.json { render json: @link, status: :created, location: @link }
      else
        format.html { redirect_to '/' }
        #format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

#  # PUT /links/1
#  # PUT /links/1.json
#  def update
#    @link = Link.find(params[:id])
#
#    respond_to do |format|
#      if @link.update_attributes(params[:link])
#        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
#        format.json { head :no_content }
#      else
#        format.html { render action: "edit" }
#        format.json { render json: @link.errors, status: :unprocessable_entity }
#      end
#    end
#  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = Link.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to "/" }
      format.json { head :no_content }
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/admins/_navbar.html.erb
<div class="row">
  <div class="navbar span4">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "Admin", admins_path, class: "brand" %>

        <ul class="nav">
          <li <%= 'class="active"'.html_safe if params[:action] == "index"%>>
            <%= link_to "All", admins_path %>
          </li>
          <li <%= 'class="active"'.html_safe if params[:action] == "new"%>>
            <%= link_to "Create", new_admin_path %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/admins/index.html.erb
<%= render 'admins/navbar' %>

<section>
  <% if @admins.any? %>
    <table class="table table-striped">
      <tr>
        <th>Name</th>
      </tr>
      <% @admins.each do |admin| %>
        <tr>
          <td><p><%= admin.name %></p></td>
        </tr>
      <% end %>
    </table>
  <% else %>
    <h3>There are no admins.</h3>
  <% end %>
</section>

app/views/admins/new.html.erb
<%= render 'admins/navbar' %>

<section>
  <div class="row">
    <div class="span4">
      <%= form_for(@admin) do |f| %>
        <%= render 'shared/error_messages' %>

        <div class="control-group">
          <div class="controls">
            <%= f.text_field :name,
                  placeholder: :name.capitalize,
                  class: "span4" %>
          </div>
        </div>

        <div class="control-group">
          <div class="controls">
            <%= f.text_field :email,
                  placeholder: :email.capitalize,
                  class: "span4" %>
          </div>
        </div>

        <div class="control-group">
          <div class="controls">
            <%= f.password_field :password,
                  placeholder: :password.capitalize,
                  class: "span4" %>
          </div>
        </div>

        <div class="control-group">
          <div class="controls">
            <%= f.password_field :password_confirmation,
                  placeholder: "Password Confirmation",
                  class: "span4" %>
          </div>
        </div>

        <div class="form-actions">
          <%= f.submit "Create", class: "btn btn-primary btn-large" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/admins/show.html.erb
<%= render 'admins/navbar' %>

<section class="row">
  <div class="hero-unit span4">
    <h1><small>Name:</small><%= @admin.name %></h1>
    <h2><span class="muted">Email: </span><%= @admin.email %></h2>
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer>
  <h5>&copy; 2013 | a <%= link_to "nullsix", "http://www.nullsix.com" %> passion</h5>
  <h6 class="muted">icons from <%= link_to "glyphicons", "http://www.glyphicons.com" %><h6>
  <% if Rails.env.development? %>
    <div style="text-align: left;">
      <%= debug(params) %>
    </div>
  <% end %>
</footer>

app/views/layouts/_header.html.erb
<header id="overview" class="jumbotron subhead">
  <h1>nullsix tagger</h1>
  <p class="lead muted">Donate to nullsix by ordering via a link tagged below!</p>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>nullsix tagger</title>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/stylesheets' %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="span12">
        <%= render 'layouts/header' %>

        <%= yield %>

        <%= render 'layouts/footer' %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/links/_form.html.erb
<section>
  <div id="tagger">
    <%= form_for(@link, :html => { class: 'form-inline' }) do |f| %>
      <div class="control-group">
        <div class="controls">
          <%= f.text_field :url,
                class: "input-large span8",
                placeholder: "Amazon URL" %>
          <%= f.button "tag!", class: "btn btn-primary btn-large", type: "submit" %>
        </div>
      </div>
    <% end %>

    <% if flash[:created] %>
      <section>
        <h1><small>Tagged Link: </small><%= link_to @tagged_link.url, @tagged_link.url %></h1>
      </section>
    <% end %>
  </div>
</section>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<%= render 'form' %>

<% if !@links.empty? %>
  <section>
    <table class="table table-striped">
      <thead>
        <tr>
          <td colspan="2">
            <h3>recently tagged links</h3>
          </td>
        </tr>
      </thead>
      <tbody>

        <% @links.each do |link| %>
          <tr class="bottom-padding-small">
            <td>
              <%= link_to "<i class=\"icon-trash icon-white\"></i>".html_safe, link,
                    method: :delete,
                    class: "btn btn-mini btn-danger" %>
            </td>
            <td>
              <h4><%= link_to link.url, link.url, style: "word-wrap:break-word;" %></h4>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>
  </section>
<% end %>

app/views/links/new.html.erb
<h1>New link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @link.url %>
</p>


<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>

app/views/shared/_error_messages.html.erb
<% if @admin.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(@admin.errors.count, "error") %>
      kept this admin from being saved:</h3>
    <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>